### ISSUE TITLE
3.4.2.stable

### ISSUE THREAD

**Issue by keithkuk** [Restream/redmine_issue_checklist#27]
/var/www/html/redmine/plugins/redmine_issue_checklist/init.rb:24: warning: key :issue_checklist is duplicated and overwritten on line 24

**Comment by adrianobr** [comment]
+1

**Comment by pflaeging** [comment]
+1

**Comment by mathisoneric** [comment]
redmine@localhost:~/redmine$  bundle exec rake redmine:plugins:migrate RAILS_ENV=production
/home/redmine/redmine/plugins/redmine_issue_checklist/init.rb:24: warning: key :issue_checklist is duplicated and overwritten on line 24
rake aborted!
NoMethodError: undefined method `alias_method_chain' for Issue (call 'Issue.connection' to establish a connection):Class
Did you mean?  alias_method
/home/redmine/redmine/plugins/redmine_issue_checklist/lib/redmine_issue_checklist/patches/issue_patch.rb:11:in `block in included'
/home/redmine/redmine/plugins/redmine_issue_checklist/lib/redmine_issue_checklist/patches/issue_patch.rb:10:in `class_eval'
/home/redmine/redmine/plugins/redmine_issue_checklist/lib/redmine_issue_checklist/patches/issue_patch.rb:10:in `included'
/home/redmine/redmine/plugins/redmine_issue_checklist/lib/redmine_issue_checklist/patches/issue_patch.rb:58:in `include'
/home/redmine/redmine/plugins/redmine_issue_checklist/lib/redmine_issue_checklist/patches/issue_patch.rb:58:in `<top (required)>'
/home/redmine/redmine/plugins/redmine_issue_checklist/lib/redmine_issue_checklist/redmine_issue_checklist.rb:5:in `block in <top (required)>'
/home/redmine/redmine/config/environment.rb:14:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
